#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Weather.Resource", IsApplication=true)]

namespace Weather
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int a20plus = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int a30plus = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int a8to15 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bonus = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bonus2 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int chanceflurries = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int chancerain = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int chancesleet = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int chancesnow = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int chancetstorms = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int clear = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int cloudy = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int flurries = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int fog = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int haze = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Home = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_action_overflow = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Icon = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int info = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Inne = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int intro = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int mostlycloudy = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int mostlysunny = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int Niedoradz = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int partlycloudy = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int partlysunny = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Pila = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int Poznan = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int rain = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int sleet = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int snow = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int sunny = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int tstorms = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int umbrella = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int under8 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int unknown = 2130837539;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int FirstLayout = 2131165184;
			
			// aapt resource value: 0x7f07002c
			public const int ListViewDailyForeCast = 2131165228;
			
			// aapt resource value: 0x7f070028
			public const int ListViewHourlyForeCast = 2131165224;
			
			// aapt resource value: 0x7f070026
			public const int SecondLayout = 2131165222;
			
			// aapt resource value: 0x7f07002b
			public const int ThirdLayout = 2131165227;
			
			// aapt resource value: 0x7f070005
			public const int btnGps = 2131165189;
			
			// aapt resource value: 0x7f07001d
			public const int btnPickPhoto = 2131165213;
			
			// aapt resource value: 0x7f070020
			public const int btnSendPhoto = 2131165216;
			
			// aapt resource value: 0x7f070004
			public const int btnSerach = 2131165188;
			
			// aapt resource value: 0x7f07001c
			public const int btnTakePhoto = 2131165212;
			
			// aapt resource value: 0x7f070012
			public const int imUmbrella = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int imageView1 = 2131165203;
			
			// aapt resource value: 0x7f070015
			public const int imgWeatherIconFCL = 2131165205;
			
			// aapt resource value: 0x7f070029
			public const int item_subtitle = 2131165225;
			
			// aapt resource value: 0x7f07002a
			public const int item_title = 2131165226;
			
			// aapt resource value: 0x7f07000e
			public const int lblConditionText = 2131165198;
			
			// aapt resource value: 0x7f070027
			public const int lblForeCastHeadingTxt = 2131165223;
			
			// aapt resource value: 0x7f070017
			public const int lblHighFCL = 2131165207;
			
			// aapt resource value: 0x7f07000b
			public const int lblHumidity = 2131165195;
			
			// aapt resource value: 0x7f070001
			public const int lblLabel = 2131165185;
			
			// aapt resource value: 0x7f07000a
			public const int lblLine1WC = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int lblLine2WC = 2131165196;
			
			// aapt resource value: 0x7f070018
			public const int lblLowFCL = 2131165208;
			
			// aapt resource value: 0x7f07001a
			public const int lblRainFCL = 2131165210;
			
			// aapt resource value: 0x7f07000f
			public const int lblSunrise = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int lblSunset = 2131165200;
			
			// aapt resource value: 0x7f070019
			public const int lblTempFCL = 2131165209;
			
			// aapt resource value: 0x7f070008
			public const int lblTempWC = 2131165192;
			
			// aapt resource value: 0x7f070016
			public const int lblTextFCL = 2131165206;
			
			// aapt resource value: 0x7f070011
			public const int lblWearIt = 2131165201;
			
			// aapt resource value: 0x7f07001b
			public const int lblWindFCL = 2131165211;
			
			// aapt resource value: 0x7f070014
			public const int lbldateDayFCL = 2131165204;
			
			// aapt resource value: 0x7f070002
			public const int linear = 2131165186;
			
			// aapt resource value: 0x7f07000d
			public const int llImgWraper = 2131165197;
			
			// aapt resource value: 0x7f070007
			public const int llWeatherDataTxt = 2131165191;
			
			// aapt resource value: 0x7f07002d
			public const int menu = 2131165229;
			
			// aapt resource value: 0x7f07001e
			public const int myImageView = 2131165214;
			
			// aapt resource value: 0x7f070025
			public const int pager = 2131165221;
			
			// aapt resource value: 0x7f070006
			public const int rlTopMainContainer = 2131165190;
			
			// aapt resource value: 0x7f070023
			public const int sliding_tabs = 2131165219;
			
			// aapt resource value: 0x7f070022
			public const int textView1 = 2131165218;
			
			// aapt resource value: 0x7f07001f
			public const int txtConditions = 2131165215;
			
			// aapt resource value: 0x7f070021
			public const int txtResponse = 2131165217;
			
			// aapt resource value: 0x7f070003
			public const int txtSearch = 2131165187;
			
			// aapt resource value: 0x7f070009
			public const int version = 2131165193;
			
			// aapt resource value: 0x7f070024
			public const int viewpager = 2131165220;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int First = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ForecastCustomLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ForecastHourly = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Fourth = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int fragment_sample = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Second = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int tab = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Third = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int actionbar_main = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
